export default [
  'ad_types',
  'categories',
  'compensation_plans',
  'customers',
  'fields',
  'finding_lines',
  'headings',
  'local_foreigns',
  'order_lines',
  'orders',
  'order_statuses',
  'page_types',
  'pay_plans',
  'primary_books',
  'sales_reps',
  'source_books',
  'udacs'
]
