// Listen for:

// PAGE_CHANGE
// CHANGE_CUSTOMER_FILTER
// CHANGE_CUSTOMER_SORT
// SAVE_CUSTOMER
    // Fire:
    // SAVE_DUPLICATE_CUSTOMER_DONE
    // SAVE_EDITED_CUSTOMER_DONE
    // SAVE_NEW_CUSTOMER_DONE
    // DELETE_CUSTOMER_DONE


